In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a = np.arange(1,13,2)

In [5]:
a

array([ 1,  3,  5,  7,  9, 11])

In [8]:
a = np.linspace(1,12,10)

In [9]:
a

array([ 1.        ,  2.22222222,  3.44444444,  4.66666667,  5.88888889,
        7.11111111,  8.33333333,  9.55555556, 10.77777778, 12.        ])

In [12]:
arr = [1,3,5,7,11,13,17,19]

In [13]:
a = np.array(arr)

In [14]:
a

array([ 1,  3,  5,  7, 11, 13, 17, 19])

In [16]:
a = a.reshape(2,4)

In [17]:
a

array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])

In [18]:
a = a.reshape(4,2)

In [19]:
a

array([[ 1,  3],
       [ 5,  7],
       [11, 13],
       [17, 19]])

In [20]:
a.size()


TypeError: 'int' object is not callable

In [21]:
a.size

8

In [22]:
a.shape

(4, 2)

In [24]:
b = np.array([(1,2), (3,4), (5,6), (7,8)])

In [25]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
a<4

array([[ True,  True],
       [False, False],
       [False, False],
       [False, False]])

In [27]:
b<4

array([[ True,  True],
       [ True, False],
       [False, False],
       [False, False]])

In [28]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
b*3

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [30]:
b+5

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [31]:
a = np.zeros(10)

In [32]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
a = np.ones(10)

In [34]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
a = np.eye(2)

In [38]:
a

array([[1., 0.],
       [0., 1.]])

In [39]:
a = np.random.randint(0,10,5)

In [40]:
a

array([5, 7, 5, 8, 9])

In [45]:
a = np.array([1,2,3], dtype = np.float)

In [46]:
a

array([1., 2., 3.])

In [42]:
a

array([1, 2, 3])

In [47]:
a = np.array([1,2,3,4,5,6])

In [48]:
a

array([1, 2, 3, 4, 5, 6])

In [49]:
a.min()

1

In [50]:
a.max()

6

In [51]:
a.sum()

21

In [52]:
a.mean()

3.5

In [53]:
a.var()

2.9166666666666665

In [54]:
a.std()

1.707825127659933

In [55]:
a.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [56]:
a.sum(axis=0)

21

In [58]:
a = a.reshape(3,2)

In [59]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
a.sum()

21

In [61]:
a.sum(axis=0)

array([ 9, 12])

In [63]:
a.sum(axis=1)

array([ 3,  7, 11])

In [64]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])